/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.core.temperature.vo.screen;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author felipe
 */
public class TemperatureDisplay extends javax.swing.JFrame {

    public TemperatureDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaTemperature = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        menuItemVersion = new javax.swing.JMenu();
        menuItemAuthor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Core Temperature");
        setBackground(new java.awt.Color(137, 148, 159));
        setResizable(false);

        areaTemperature.setEditable(false);
        areaTemperature.setBackground(new java.awt.Color(1, 1, 1));
        areaTemperature.setColumns(15);
        areaTemperature.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        areaTemperature.setForeground(new java.awt.Color(25, 201, 69));
        areaTemperature.setRows(4);
        jScrollPane1.setViewportView(areaTemperature);

        menuItemVersion.setText("About");

        menuItemAuthor.setText("Author");
        menuItemAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAuthorActionPerformed(evt);
            }
        });
        menuItemVersion.add(menuItemAuthor);

        jMenuItem1.setText("Version");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuItemVersion.add(jMenuItem1);

        menuBar.add(menuItemVersion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Version 1.0.0");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAuthorActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Felipe Vieira Mota - felipevieiramota@gmail.com");
    }//GEN-LAST:event_menuItemAuthorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTemperature;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAuthor;
    private javax.swing.JMenu menuItemVersion;
    // End of variables declaration//GEN-END:variables

    public void setAboutMenuItem(JMenu aboutMenuItem) {
        this.menuItemVersion = aboutMenuItem;
    }

    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    public JMenu getAboutMenuItem() {
        return menuItemVersion;
    }

    public JTextArea getAreaTemperature() {
        return areaTemperature;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setAreaTemperature(JTextArea areaTemperature) {
        this.areaTemperature = areaTemperature;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }    
}
